name: Java CI
run-name: ${{ github.actor }} is launching a build
on: 
  push:
    branches: [ develop ]
jobs:
  build_and_deploy:
    runs-on: ubuntu-18.04
    environment: 
      name: tse-cf    
    steps:
      - name: Check out repository code    
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: maven-settings-xml-action
        uses: s4u/maven-settings-action@v2.8.0
#        with:
#          servers: |
#            [{
#            "id": "github-packages-server",
#            "username": "${{ secrets.GITHUB_PACKAGES_USERNAME }}",
#            "password": "${{ secrets.GITHUB_PACKAGES_PASSWORD }}"
#            }]
      - name: check settings.xml
        id: vars
        run: cat /home/runner/.m2/settings.xml
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package   
#      - name: List files in the repository
#        run: |
#          ls -altr ${{ github.workspace }}
#      - name: Keep build dir          
#      - uses: actions/cache@v2
#        id: cache-build
#        with:
#          path: ./*
#          key: ${{ github.sha }}          
      - name: Deploy in Cloud Foundry
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: push cf-hello-world -f /github/workspace/manifest.yml
       
